### ISSUE TITLE
Прогресс начального заполнения таблиц истории звонков

### ISSUE THREAD

**Issue by boffart** [mikopbx/ModuleExtendedCDRs#2]
Модуль установили и включили, а данных-то оказывается, нет, и нет, и нет!? Так что по-доброму хорошо было бы на это время высвечивать плакатик, что мол идет первичное наполнение, подождите. Ну, про прогресс-индикатор только помечтать... Вчера я не дождался, ушел спать. Утром все в порядке!

**Comment by boffart** [comment]
готово

**Comment by MrLyu49** [comment]
Отлично, но к сожалению, первичное наполнение уже сделано, так что проверить не могу...
