### ISSUE TITLE
Сортировка списка выбора сотрудника

### ISSUE THREAD

**Issue by boffart** [mikopbx/ModuleExtendedCDRs#3]
При выборе сотрудников их список вываливается неотсортированным ни по номерам, ни по фамилиям. Похоже, просто по порядку их заведения в системе. Хорошо бы делать сортировку. Идеально с возможностью выбора критерия или хотя бы просто по именам (как список дается на вкладке Сотрудники).

**Comment by boffart** [comment]
Готово

**Comment by MrLyu49** [comment]
Хорошо, сортировка появилась. Но не в том порядке, как по умолчанию в основном списке Сотрудники - там по именам, а тут по номерам. Разнобой! Но идеально было бы сделать выбор критерия сортировки, как в основном списке Сотрудники.
