### ISSUE TITLE
Некорректное отображение истории звонков. "Пустые строки в таблице"

### ISSUE THREAD

**Issue by boffart** [mikopbx/ModuleExtendedCDRs#5]
История (нерасширенная) показывает 55 вызовов. 

Расширенная показывает ровно те же самые 55 вызовов, но пишет о показе 76 вызовов. И последние 21 - пустые строки в таблице, из-за чего последняя страница показа истории вообще целиком пустая! Я обратил внимание, что 76 - это полное число вызовов, а 55 - вызовы разрешенных сотрудников.

**Comment by MrLyu49** [comment]
Поясню, речь о работе с модулем расширенной истории через модуль управления доступом.

**Comment by boffart** [comment]
не могу воспроизвести эту проблему

**Comment by MrLyu49** [comment]
В версии модуля 1.17 пустые строки (и целые пустые страницы в конце истории) по-прежнему появляются, если при работе через модуль управления доступом модуль расширенной истории показывает не все звонки, а только разрешенных сотрудников. Эффект устойчивый.
![расшир_история](https://github.com/user-attachments/assets/f13caeed-17ea-400b-b9a6-9906e3c8c4d5)

**Comment by boffart** [comment]
В 1.30 версии исправлено

**Comment by MrLyu49** [comment]
Да, в 1.30 это исправлено, но появилась другая проблема - теперь невозможно переставить пункт для этого модуля в основном меню на другое место. А хотелось бы в раздел Телефония.
