### ISSUE TITLE
Некорректный статус звонки при ответе сотрудника на мобильный. 

### ISSUE THREAD

**Issue by boffart** [mikopbx/ModuleExtendedCDRs#6]
Еще недоработка. Сотрудник звонит другому сотруднику, но того нет на мессте и звонок переадресовывается на его мобильный. Там сотрудник ответил, успешно поговорили, но модуль показывает статус "недозвон". Надо бы поправить.

**Comment by boffart** [comment]
Готово.

**Comment by MrLyu49** [comment]
Отлично, спасибо!
